name: playerctl
base: core18
version: '2.2.1+git'
summary: Media player command-line controller
description: |
  Playerctl is a command-line utility and library for controlling media players
  that implement the MPRIS D-Bus Interface Specification. Playerctl makes it
  easy to bind player actions, such as play and pause, to media keys. You can
  also get metadata about the playing track such as the artist and title for
  integration into statusline generators or other command-line tools.

grade: devel
confinement: strict

parts:
  playerctl:
    plugin: meson
    source: https://github.com/altdesktop/playerctl
    source-type: git
    meson-parameters:
      - -Dintrospection=false
      - -Dgtk-doc=false
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-0

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: org.mpris.MediaPlayer2.playerctld

apps:
  playerctl:
    command: playerctl
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET

  playerctld:
    command: playerctld
    slots: [ dbus-svc ]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET
